# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'propertyDisplay' do

  use_frameworks!

    pod 'Alamofire', '~> 4.5'
    pod 'SwiftyJSON'
#    pod 'PZPullToRefresh'
    pod 'SVProgressHUD'
    pod 'Localize-Swift', '~> 2.0'
    pod 'ObjectMapper'
    pod 'Kingfisher'
    pod 'ImagePicker'

end
